services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - SITE_DOMAINS=${SITE_DOMAINS}
      - EMAIL=${EMAIL}
      - PHONE_NUMBER=${PHONE_NUMBER}
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
